name: dharnetttest
favicon: null
layout_spectrum: 0.21304
typography_spectrum: 0.40316
title: kuhoh
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#f1f1f1'
    - '#ed6c37'
    - '#4a4a4a'
    - '#979797'
  brandStrength: 1
  lightness: 0.8312967594247311
  saturation: 0.31038542417809367
  rhythmicContrast: 0.3625850572716445
purpose: []
