name: dharnetttest
favicon: null
layout_spectrum: 0.06612717220559716
typography_spectrum: 0.3196921197231859
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9728214694187045
  lightness: 0.8312967594247311
  saturation: 0.31038542417809367
  rhythmicContrast: 0.3625850572716445
purpose: []
